// packages/angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'io-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-demo';
}

<io-button appearance="primary">Primary</io-button>
<io-button appearance="secondary">Secondary</io-button>
<io-button appearance="tertiary">Tertiary</io-button>
<io-button appearance="warning">Warning</io-button>
<io-button appearance="danger">Danger</io-button>
<io-button appearance="flat">Flat</io-button>

// packages/react-demo/src/app/app.tsx
import { IoButton } from '@io/web-components-react';

export function App() {
    return (
        <>
            <IoButton appearance='primary'>Primary</IoButton>
            <IoButton appearance='secondary'>Secondary</IoButton>
            <IoButton appearance='tertiary'>Tertiary</IoButton>
            <IoButton appearance='warning'>Warning</IoButton>
            <IoButton appearance='danger'>Danger</IoButton>
            <IoButton appearance='flat'>Flat</IoButton>
        </>
    );
}

export default App;
